### ISSUE TITLE
[Anon] Bug report: Barbarians.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/warlords-of-erehwon#10]
**File:** Barbarians.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Barbarian stone thrower artillery only records the large stone thrower upgrade value of 27 points when small stone thrower is selected. It should be 81 for the small stone thrower and 81+27 for a large stone thrower

The value for a basic small stone thrower should add 81 points to your to total force cost...it only adds 27

**Comment by LeadAddict** [comment]
Thanks for the report, I am pushing a new version with a fix. It should be available in Battlescribe in a few hours.
